package views;

import java.awt.Color;
import java.awt.Frame;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.plaf.RootPaneUI;
/**
 *
 */
public class menuUtama extends javax.swing.JFrame {
        
    // waktu sekarang 
     private void setJam(){
        ActionListener listener = new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent evt) {
                jam.setText(new WaktuSekarang().getWkt());
            }
        };
        new Timer(1000, listener).start();
    }
    // penutup waktu sekarang
     
    // frame maks dan geser panel
    static boolean maximixed = true;
    int xMouse;
    int yMouse;
// penutup frame maks dan geser panel
    

    
    public menuUtama() {
        initComponents();
        setJam();
        panelMasterData.setVisible(false);
        panelTransaksi.setVisible(false);
        panelLaporan.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        labelNama = new javax.swing.JLabel();
        btnMaximize = new javax.swing.JButton();
        btnMinimize = new javax.swing.JButton();
        panelMenu = new javax.swing.JPanel();
        btnMasterData = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        panelJam = new javax.swing.JPanel();
        tgl = new javax.swing.JLabel();
        jam = new javax.swing.JLabel();
        jPanel1 = new views.background();
        panelMasterData = new javax.swing.JPanel();
        btnDataAset = new javax.swing.JButton();
        btnDataRuang = new javax.swing.JButton();
        panelTransaksi = new javax.swing.JPanel();
        btnAsetMasuk = new javax.swing.JButton();
        btnAsetKeluar = new javax.swing.JButton();
        panelLaporan = new javax.swing.JPanel();
        btnLapAsetMasuk = new javax.swing.JButton();
        btnLapAsetKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panelUtama.setBackground(new java.awt.Color(240, 240, 240));
        panelUtama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelUtamaMouseClicked(evt);
            }
        });

        panelHeader.setBackground(new java.awt.Color(252, 187, 109));

        btnClose.setBackground(new java.awt.Color(252, 187, 109));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Delete_30px_4.png"))); // NOI18N
        btnClose.setContentAreaFilled(false);
        btnClose.setOpaque(true);
        btnClose.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Delete_30px_5.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        labelNama.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        labelNama.setForeground(new java.awt.Color(51, 51, 51));
        labelNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNama.setText("Aplikasi Inventaris Aset PT Digital Banua");
        labelNama.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                labelNamaMouseDragged(evt);
            }
        });
        labelNama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelNamaMousePressed(evt);
            }
        });

        btnMaximize.setBackground(new java.awt.Color(102, 102, 102));
        btnMaximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Maximize_Window_30px.png"))); // NOI18N
        btnMaximize.setContentAreaFilled(false);
        btnMaximize.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Maximize_Window_30px_1.png"))); // NOI18N
        btnMaximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaximizeMouseClicked(evt);
            }
        });

        btnMinimize.setBackground(new java.awt.Color(204, 204, 204));
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Minimize_Window_30px.png"))); // NOI18N
        btnMinimize.setContentAreaFilled(false);
        btnMinimize.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Minimize_Window_30px_1.png"))); // NOI18N
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addComponent(labelNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMaximize, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
            .addComponent(btnMaximize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMinimize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));

        btnMasterData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMasterData.setForeground(new java.awt.Color(51, 51, 51));
        btnMasterData.setText("  Master Data");
        btnMasterData.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnMasterData.setContentAreaFilled(false);
        btnMasterData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMasterData.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMasterData.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMasterData.setOpaque(true);
        btnMasterData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMasterDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMasterDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMasterDataMouseExited(evt);
            }
        });

        btnTransaksi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTransaksi.setForeground(new java.awt.Color(51, 51, 51));
        btnTransaksi.setText("  Transaksi");
        btnTransaksi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnTransaksi.setContentAreaFilled(false);
        btnTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTransaksi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTransaksi.setOpaque(true);
        btnTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseExited(evt);
            }
        });

        btnLaporan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLaporan.setForeground(new java.awt.Color(51, 51, 51));
        btnLaporan.setText("  Laporan");
        btnLaporan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLaporan.setContentAreaFilled(false);
        btnLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLaporan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLaporan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLaporan.setOpaque(true);
        btnLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLaporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLaporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLaporanMouseExited(evt);
            }
        });

        panelJam.setBackground(new java.awt.Color(255, 255, 255));

        tgl.setBackground(new java.awt.Color(255, 255, 255));
        tgl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tgl.setForeground(new java.awt.Color(51, 51, 51));
        tgl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tgl.setOpaque(true);

        jam.setBackground(new java.awt.Color(255, 255, 255));
        jam.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jam.setForeground(new java.awt.Color(51, 51, 51));
        jam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jam.setOpaque(true);

        javax.swing.GroupLayout panelJamLayout = new javax.swing.GroupLayout(panelJam);
        panelJam.setLayout(panelJamLayout);
        panelJamLayout.setHorizontalGroup(
            panelJamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tgl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
            .addComponent(jam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelJamLayout.setVerticalGroup(
            panelJamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJamLayout.createSequentialGroup()
                .addComponent(jam, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tgl.setText(new WaktuSekarang().getTgl());
        tgl.setPreferredSize(new java.awt.Dimension(120,22));
        jam.setText(new WaktuSekarang().getWkt());
        jam.setPreferredSize(new java.awt.Dimension(100,22));

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnMasterData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(btnTransaksi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(btnLaporan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(panelJam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnMasterData, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelMasterData.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnDataAset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDataAset.setForeground(new java.awt.Color(51, 51, 51));
        btnDataAset.setText("  > Data Aset");
        btnDataAset.setToolTipText("");
        btnDataAset.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnDataAset.setContentAreaFilled(false);
        btnDataAset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDataAset.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDataAset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDataAset.setOpaque(true);
        btnDataAset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDataAsetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDataAsetMouseExited(evt);
            }
        });
        btnDataAset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataAsetActionPerformed(evt);
            }
        });

        btnDataRuang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDataRuang.setForeground(new java.awt.Color(51, 51, 51));
        btnDataRuang.setText("  > Data Ruang");
        btnDataRuang.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnDataRuang.setContentAreaFilled(false);
        btnDataRuang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDataRuang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDataRuang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDataRuang.setOpaque(true);
        btnDataRuang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDataRuangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDataRuangMouseExited(evt);
            }
        });
        btnDataRuang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataRuangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMasterDataLayout = new javax.swing.GroupLayout(panelMasterData);
        panelMasterData.setLayout(panelMasterDataLayout);
        panelMasterDataLayout.setHorizontalGroup(
            panelMasterDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDataAset, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(btnDataRuang, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        panelMasterDataLayout.setVerticalGroup(
            panelMasterDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMasterDataLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDataAset, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btnDataRuang, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelTransaksi.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnAsetMasuk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAsetMasuk.setForeground(new java.awt.Color(51, 51, 51));
        btnAsetMasuk.setText("  > Aset Masuk");
        btnAsetMasuk.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAsetMasuk.setContentAreaFilled(false);
        btnAsetMasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAsetMasuk.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAsetMasuk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAsetMasuk.setOpaque(true);
        btnAsetMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAsetMasukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAsetMasukMouseExited(evt);
            }
        });
        btnAsetMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsetMasukActionPerformed(evt);
            }
        });

        btnAsetKeluar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAsetKeluar.setForeground(new java.awt.Color(51, 51, 51));
        btnAsetKeluar.setText("  > Aset Keluar");
        btnAsetKeluar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAsetKeluar.setContentAreaFilled(false);
        btnAsetKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAsetKeluar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAsetKeluar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAsetKeluar.setOpaque(true);
        btnAsetKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAsetKeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAsetKeluarMouseExited(evt);
            }
        });
        btnAsetKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsetKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTransaksiLayout = new javax.swing.GroupLayout(panelTransaksi);
        panelTransaksi.setLayout(panelTransaksiLayout);
        panelTransaksiLayout.setHorizontalGroup(
            panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAsetKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(btnAsetMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        panelTransaksiLayout.setVerticalGroup(
            panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransaksiLayout.createSequentialGroup()
                .addComponent(btnAsetMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAsetKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelLaporan.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnLapAsetMasuk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLapAsetMasuk.setForeground(new java.awt.Color(51, 51, 51));
        btnLapAsetMasuk.setText("  > Laporan Aset Masuk");
        btnLapAsetMasuk.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLapAsetMasuk.setContentAreaFilled(false);
        btnLapAsetMasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLapAsetMasuk.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLapAsetMasuk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLapAsetMasuk.setOpaque(true);
        btnLapAsetMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLapAsetMasukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLapAsetMasukMouseExited(evt);
            }
        });
        btnLapAsetMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapAsetMasukActionPerformed(evt);
            }
        });

        btnLapAsetKeluar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLapAsetKeluar.setForeground(new java.awt.Color(51, 51, 51));
        btnLapAsetKeluar.setText("  > Laporan Aset Keluar");
        btnLapAsetKeluar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLapAsetKeluar.setContentAreaFilled(false);
        btnLapAsetKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLapAsetKeluar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLapAsetKeluar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLapAsetKeluar.setOpaque(true);
        btnLapAsetKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLapAsetKeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLapAsetKeluarMouseExited(evt);
            }
        });
        btnLapAsetKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapAsetKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLaporanLayout = new javax.swing.GroupLayout(panelLaporan);
        panelLaporan.setLayout(panelLaporanLayout);
        panelLaporanLayout.setHorizontalGroup(
            panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLapAsetKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(btnLapAsetMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        panelLaporanLayout.setVerticalGroup(
            panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLaporanLayout.createSequentialGroup()
                .addComponent(btnLapAsetMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnLapAsetKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMasterData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(996, Short.MAX_VALUE))
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addComponent(panelMasterData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(panelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(panelLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 330, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        btnClose.setBackground(Color.red);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        btnClose.setBackground(new Color(252,187,109));
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        String ObjButton[] = {"YES","NO"};
        int pilihan = JOptionPane.showOptionDialog(null,"Apakah Anda yakin ingi keluar?","Message", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
                null,ObjButton,ObjButton[1]);
        if(pilihan == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        btnMinimize.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnMasterDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasterDataMouseClicked
        panelMasterData.setVisible(true);
        panelTransaksi.setVisible(false);
        panelLaporan.setVisible(false);
    }//GEN-LAST:event_btnMasterDataMouseClicked

    private void btnTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseClicked
        panelTransaksi.setVisible(true);
        panelMasterData.setVisible(false);
        panelLaporan.setVisible(false);
    }//GEN-LAST:event_btnTransaksiMouseClicked

    private void btnLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseClicked
        panelLaporan.setVisible(true);
        panelTransaksi.setVisible(false);
        panelMasterData.setVisible(false);
    }//GEN-LAST:event_btnLaporanMouseClicked

    private void btnDataAsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataAsetActionPerformed
        panelMasterData.setVisible(false);
        new dataAset(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnDataAsetActionPerformed

    private void panelUtamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUtamaMouseClicked
        panelMasterData.setVisible(false);
        panelTransaksi.setVisible(false);
        panelLaporan.setVisible(false);
    }//GEN-LAST:event_panelUtamaMouseClicked

    private void btnMasterDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasterDataMouseEntered
        btnMasterData.setForeground(Color.black);
        btnMasterData.setBackground(new Color(235,235,235));
    }//GEN-LAST:event_btnMasterDataMouseEntered

    private void btnMasterDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasterDataMouseExited
        btnMasterData.setForeground(Color.black);
        btnMasterData.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnMasterDataMouseExited

    private void btnTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseEntered
        btnTransaksi.setForeground(Color.black);
        btnTransaksi.setBackground(new Color(235,235,235));
    }//GEN-LAST:event_btnTransaksiMouseEntered

    private void btnTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseExited
        btnTransaksi.setForeground(Color.black);
        btnTransaksi.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnTransaksiMouseExited

    private void btnLaporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseEntered
        btnLaporan.setForeground(Color.black);
        btnLaporan.setBackground(new Color(235,235,235));
    }//GEN-LAST:event_btnLaporanMouseEntered

    private void btnLaporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseExited
        btnLaporan.setForeground(Color.black);
        btnLaporan.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnLaporanMouseExited

    private void btnDataAsetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataAsetMouseEntered
        btnDataAset.setForeground(Color.black);
        btnDataAset.setBackground(new Color(235,235,235));
    }//GEN-LAST:event_btnDataAsetMouseEntered

    private void btnDataAsetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataAsetMouseExited
        btnDataAset.setForeground(Color.black);
        btnDataAset.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnDataAsetMouseExited

    private void btnDataRuangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataRuangMouseEntered
        btnDataRuang.setForeground(Color.black);
        btnDataRuang.setBackground(new Color(235,235,235));
    }//GEN-LAST:event_btnDataRuangMouseEntered

    private void btnDataRuangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataRuangMouseExited
        btnDataRuang.setForeground(Color.black);
        btnDataRuang.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnDataRuangMouseExited

    private void btnAsetMasukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsetMasukMouseEntered
        btnAsetMasuk.setForeground(Color.black);
        btnAsetMasuk.setBackground(new Color(235,235,235));
    }//GEN-LAST:event_btnAsetMasukMouseEntered

    private void btnAsetMasukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsetMasukMouseExited
        btnAsetMasuk.setForeground(Color.black);
        btnAsetMasuk.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnAsetMasukMouseExited

    private void btnAsetKeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsetKeluarMouseEntered
        btnAsetKeluar.setForeground(Color.black);
        btnAsetKeluar.setBackground(new Color(235,235,235));
    }//GEN-LAST:event_btnAsetKeluarMouseEntered

    private void btnAsetKeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsetKeluarMouseExited
        btnAsetKeluar.setForeground(Color.black);
        btnAsetKeluar.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnAsetKeluarMouseExited

    private void btnLapAsetMasukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapAsetMasukMouseEntered
        btnLapAsetMasuk.setForeground(Color.black);
        btnLapAsetMasuk.setBackground(new Color(235,235,235));
    }//GEN-LAST:event_btnLapAsetMasukMouseEntered

    private void btnLapAsetMasukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapAsetMasukMouseExited
        btnLapAsetMasuk.setForeground(Color.black);
        btnLapAsetMasuk.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnLapAsetMasukMouseExited

    private void btnLapAsetKeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapAsetKeluarMouseEntered
        btnLapAsetKeluar.setForeground(Color.black);
        btnLapAsetKeluar.setBackground(new Color(235,235,235));
    }//GEN-LAST:event_btnLapAsetKeluarMouseEntered

    private void btnLapAsetKeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapAsetKeluarMouseExited
        btnLapAsetKeluar.setForeground(Color.black);
        btnLapAsetKeluar.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnLapAsetKeluarMouseExited

    private void btnMaximizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizeMouseClicked
        if(maximixed){
            menuUtama.this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
            menuUtama.this.setMaximizedBounds(env.getMaximumWindowBounds());
            maximixed = false;
        } else {
            setExtendedState(JFrame.NORMAL);
            maximixed = true;
        }
    }//GEN-LAST:event_btnMaximizeMouseClicked

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void labelNamaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNamaMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_labelNamaMousePressed

    private void labelNamaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNamaMouseDragged
        if(maximixed){
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            this.setLocation(x - xMouse, y - yMouse);
        }
    }//GEN-LAST:event_labelNamaMouseDragged

    private void btnDataRuangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataRuangActionPerformed
        panelMasterData.setVisible(false);
        new dataRuang(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnDataRuangActionPerformed

    private void btnAsetMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsetMasukActionPerformed
        panelTransaksi.setVisible(false);
        new transaksiAsetMasuk(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnAsetMasukActionPerformed

    private void btnAsetKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsetKeluarActionPerformed
        panelTransaksi.setVisible(false);
        new transaksiAsetKeluar(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnAsetKeluarActionPerformed

    private void btnLapAsetMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapAsetMasukActionPerformed
        panelLaporan.setVisible(false);
        new laporanAsetMasuk(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnLapAsetMasukActionPerformed

    private void btnLapAsetKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapAsetKeluarActionPerformed
        panelLaporan.setVisible(false);
        new laporanAsetKeluar(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnLapAsetKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                menuUtama mn = new menuUtama();
                mn.setExtendedState(JFrame.MAXIMIZED_BOTH);
                mn.setVisible(true);
            }           
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsetKeluar;
    private javax.swing.JButton btnAsetMasuk;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDataAset;
    private javax.swing.JButton btnDataRuang;
    private javax.swing.JButton btnLapAsetKeluar;
    private javax.swing.JButton btnLapAsetMasuk;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnMasterData;
    private javax.swing.JButton btnMaximize;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jam;
    private javax.swing.JLabel labelNama;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelJam;
    private javax.swing.JPanel panelLaporan;
    private javax.swing.JPanel panelMasterData;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelTransaksi;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JLabel tgl;
    // End of variables declaration//GEN-END:variables
}
